#!/usr/bin/env bash

domain="$1"
subdomain="$2"

# Define function to print DNS record information
print_dns_record_info() {
    script=$(dig "$1"."$domain" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "The subdomain $1 is a $script record and points to $(echo $script | awk '{print $NF}')"
}

# If only domain parameter is provided
if [ $# -eq 1 ]; then
    print_dns_record_info "www"
    print_dns_record_info "lb-01"
    print_dns_record_info "web-01"
    print_dns_record_info "web-02"
# If both domain and subdomain parameters are provided
elif [ $# -eq 2 ]; then
    print_dns_record_info "$subdomain"
fi
