#!/usr/bin/env bash
# configure your nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

#code to redirect a specific endpoint (eg: redirect /redirect_me to http://damianemerah.tech)
echo "Hello World!" | sudo tee /var/www/html/index.html
str_for_replacement="s/server_name _;\n\trewrite ^\/redirect_me http:\/damianemerah.tech permenent;"
sudo sed -i "s/server_name _;/$str_for_replacement/" /etc/nginx/sites-enabled/default

#code to create error page and add a rediect for error 404
echo "Ceci n'est pas une page" | sudo too /var/www/html/404.html
str_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
